version: "3"

services:
  bot:
    build:
      context: .
      args:
        - service_src=./bot/src
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./bot/environment
    volumes:
      - ./bot/src:/usr/src/app/service/src:cached
      - ./common:/usr/src/app/common:cached
    
  planner:
    build:
      context: .
      args:
        - service_src=./planner/src
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./planner/environment
    volumes:
      - ./planner/src:/usr/src/app/service/src:cached
      - ./common:/usr/src/app/common:cached
      
  crawler:
    build:
      context: .
      args:
        - service_src=./crawler/src
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./crawler/environment
    volumes:
      - ./crawler/src:/usr/src/app/service/src:cached
      - ./common:/usr/src/app/common:cached

  comparator:
    build:
      context: .
      args:
        - service_src=./comparator/src
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./comparator/environment
    volumes:
      - ./comparator/src:/usr/src/app/service/src:cached
      - ./common:/usr/src/app/common:cached

  mongo:
    image: "mongo:latest"
    logging:
      driver: none
    ports:
      - 27017:27017

  rabbitmq:
    image: "rabbitmq:management"
    logging:
      driver: none
    ports:
      - "5672:5672"
      - "15672:15672"
